namespace PortraitFinder.Model.Enums;

[Flags]
public enum PlayerClass: long
{
    Unset = 0,
    Alchemist = 1L << 0,
    Arcanist = 1L << 1,
    Barbarian = 1L << 2,
    Bard = 1L << 3,
    Bloodrager = 1L << 4,
    Cavalier = 1L << 5,
    Cleric = 1L << 6,
    Druid = 1L << 7,
    Fighter = 1L << 8,
    Hunter = 1L << 9,
    Inquisitor = 1L << 10,
    Kineticist = 1L << 11,
    Magus = 1L << 12,
    Monk = 1L << 13,
    Oracle = 1L << 14,
    Paladin = 1L << 15,
    Ranger = 1L << 16,
    Rogue = 1L << 17,
    Shaman = 1L << 18,
    Shifter = 1L << 19,
    Skald = 1L << 20,
    Slayer = 1L << 21,
    Sorcerer = 1L << 22,
    Warpriest = 1L << 23,
    Witch = 1L << 24,
    Wizard = 1L << 25,
    AldoriSwordlord = 1L << 26,
    ArcaneTrickster = 1L << 27,
    Assassin = 1L << 28,
    Duelist = 1L << 29,
    DragonDisciple = 1L << 30,
    EldritchKnight = 1L << 31,
    Hellknight = 1L << 32,
    HellknightSignifier = 1L << 33,
    Loremaster = 1L << 34,
    MysticTheurge = 1L << 35,
    StalwartDefender = 1L << 36,
    StudentOfWar = 1L << 37,
    WinterWitch = 1L << 38
}