// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortraitFinder.Data;

#nullable disable

namespace PortraitFinder.Data.Migrations
{
    [DbContext(typeof(PortraitFinderDbContext))]
    [Migration("20260711094313_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PortraitFinder.Model.Portrait", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Armor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Companion")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HairColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HairLength")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeadFeature")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImageLastModified")
                        .HasColumnType("TEXT");

                    b.Property<int>("MythicPath")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PlayerClass")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PortraitFolderPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Race")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Surrounding")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weapon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wing")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Portraits");
                });
#pragma warning restore 612, 618
        }
    }
}
